#!/usr/bin/python3

import shutil
import subprocess
import sys

import dbus
import dbus.mainloop.glib
import dbus.service
from gi.repository import GLib

AGENT_PATH = "/org/omarchy/BluetoothAgent"
AGENT_IFACE = "org.bluez.Agent1"
AGENT_MANAGER = "org.bluez.AgentManager1"
DEVICE_IFACE = "org.bluez.Device1"
PROPS_IFACE = "org.freedesktop.DBus.Properties"
BLUEZ = "org.bluez"


def notify(headline, description):
    sender = shutil.which("omarchy-notification-send")
    if sender:
        subprocess.Popen(
            [sender, "-u", "normal", "-g", "󰂯", headline, description, "-t", "30000"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        return
    print(f"{headline}: {description}", flush=True)


def device_label(bus, path):
    try:
        props = dbus.Interface(bus.get_object(BLUEZ, path), PROPS_IFACE)
        values = props.GetAll(DEVICE_IFACE)
        return str(values.get("Name") or values.get("Alias") or path)
    except dbus.exceptions.DBusException:
        return path


class Agent(dbus.service.Object):
    def __init__(self, bus, path):
        self.bus = bus
        super().__init__(bus, path)

    def _passkey_notice(self, device, passkey):
        notify(
            f"Pair {device_label(self.bus, device)}",
            f"Type {int(passkey):06d} on the device, then press Enter.",
        )

    @dbus.service.method(AGENT_IFACE, in_signature="ou", out_signature="")
    def RequestConfirmation(self, device, passkey):
        self._passkey_notice(device, passkey)

    @dbus.service.method(AGENT_IFACE, in_signature="ouq", out_signature="")
    def DisplayPasskey(self, device, passkey, entered):
        if int(entered) == 0:
            self._passkey_notice(device, passkey)

    @dbus.service.method(AGENT_IFACE, in_signature="os", out_signature="")
    def DisplayPinCode(self, device, pincode):
        notify(
            f"Pair {device_label(self.bus, device)}",
            f"Type {pincode} on the device, then press Enter.",
        )

    @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="")
    def RequestAuthorization(self, device):
        return

    @dbus.service.method(AGENT_IFACE, in_signature="os", out_signature="")
    def AuthorizeService(self, device, uuid):
        return

    @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="s")
    def RequestPinCode(self, device):
        return "000000"

    @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="u")
    def RequestPasskey(self, device):
        return dbus.UInt32(0)

    @dbus.service.method(AGENT_IFACE, in_signature="", out_signature="")
    def Cancel(self):
        return

    @dbus.service.method(AGENT_IFACE, in_signature="", out_signature="")
    def Release(self):
        return


def main():
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    bus = dbus.SystemBus()
    Agent(bus, AGENT_PATH)
    manager = dbus.Interface(bus.get_object(BLUEZ, "/org/bluez"), AGENT_MANAGER)
    try:
        manager.UnregisterAgent(AGENT_PATH)
    except dbus.exceptions.DBusException:
        pass
    manager.RegisterAgent(AGENT_PATH, "KeyboardDisplay")
    manager.RequestDefaultAgent(AGENT_PATH)
    GLib.MainLoop().run()


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(0)
